services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: j+qc+2AIYSJHw5/obRr8EYLNw7QFKJX86WioA/S2zSk= # Only for development

volumes:
  postgres_data:
